


export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just for You",
    description:
      " Get Interview question and models answer based on your role, experience, and specific focus areas - no ",
  },
  {
    id: "02",
    title: "Learn at your own pace",
    description:
      "Expand answers only when you are ready. Dive deeper into any concept instantly with AI-powered detailed",
  },
  {
    id: "03",
    title: "Capture your Insights",
    description:
      " Add personal notes to any questions and pi important ones to top - making your learning more orgaized ",
  },
  {
    id: "04",
    title: ' Understand the "Why" behind answers ',
    description:
      " Beyound just answers - unlock detailed concept explanations generated by AI, helping you truely master  ",
  },
  {
    id: "05",
    title: "Save, Organize, and Revisit",
    description:
      " Esaily save your interview seta, organize them neatly in your dashboard, and pick up your preparation ",
  },
];